name: Release on Merge

on:
  pull_request:
    types:
      - closed

jobs:
  release:
    if: github.event.pull_request.merged == true && github.base_ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed for versioning

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Get PR labels using GitHub CLI
        id: labels
        run: |
          LABEL=$(gh api --jq '.labels[].name' /repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} | grep -E 'major|minor|patch' || echo '')

          if [[ -z "$LABEL" ]]; then
            echo "❌ No version bump label (major, minor, patch) found!"
            exit 1  # Fail the job to prevent merging
          fi

          echo "LABEL=$LABEL" >> $GITHUB_ENV
          echo "✅ Found version label: $LABEL"

      - name: Run release-it
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx release-it --ci --no-npm --increment $LABEL
